# Generated by Django 5.0.4 on 2024-05-14 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0007_livros_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livros",
            name="usuario",
        ),
    ]
