# Generated by Django 5.0.4 on 2024-05-14 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0008_remove_livros_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livros",
            old_name="co_autor",
            new_name="editora",
        ),
    ]
