# Generated by Django 5.0.4 on 2024-05-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0010_livros_usuario"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
            preserve_default=False,
        ),
    ]
