# Generated by Django 5.0.4 on 2024-05-16 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0012_remove_livros_data_devolucao_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Emprestimo",
            new_name="Emprestimos",
        ),
    ]
