# Generated by Django 5.0.4 on 2024-05-16 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0013_rename_emprestimo_emprestimos"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimos",
            name="nome_emprestado_anonimo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimos",
            name="nome_emprestado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
            preserve_default=False,
        ),
    ]
