# Generated by Django 5.0.4 on 2024-05-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0014_emprestimos_nome_emprestado_anonimo_and_more"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimos",
            name="nome_emprestado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
        ),
    ]
