# Generated by Django 5.0.4 on 2024-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0015_alter_emprestimos_nome_emprestado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimos",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimos",
            name="data_emprestimo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
