# Generated by Django 5.0.4 on 2024-05-16 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0016_alter_emprestimos_data_devolucao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprestimos",
            name="tempo_duracao",
        ),
    ]
